# Documentation
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**/*"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Docker
area/docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile*"
          - "**/.dockerignore"
          - "**/docker-compose*.yml"
          - "**/docker-compose*.yaml"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.toml"
          - "**/*.yaml"
          - "**/*.yml"
          - "**/*.json"
          - "!package*.json"
          - "!.github/**/*"

# Dependencies
area/deps:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Cargo.toml"
          - "**/Cargo.lock"

# Testing
area/testing:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tests/**/*"
          - "**/*_test.rs"
          - "**/*_tests.rs"

# Tenancy/Multi-tenant
area/tenancy:
  - changed-files:
      - any-glob-to-any-file:
          - "**/tenant/**/*"
          - "**/tenancy/**/*"
          - "**/multi-tenant/**/*"

# Vault Management
area/vault:
  - changed-files:
      - any-glob-to-any-file:
          - "**/vault/**/*"

# Session/Authentication
area/session:
  - changed-files:
      - any-glob-to-any-file:
          - "**/session/**/*"
          - "**/auth/**/*"
          - "**/authentication/**/*"

# Passkey/WebAuthn
area/passkey:
  - changed-files:
      - any-glob-to-any-file:
          - "**/passkey/**/*"
          - "**/webauthn/**/*"

# Client Management
area/client:
  - changed-files:
      - any-glob-to-any-file:
          - "**/client/**/*"

# Team Management
area/team:
  - changed-files:
      - any-glob-to-any-file:
          - "**/team/**/*"

# RBAC/Permissions
area/rbac:
  - changed-files:
      - any-glob-to-any-file:
          - "**/rbac/**/*"
          - "**/permissions/**/*"
          - "**/roles/**/*"

# Audit Logging
area/audit:
  - changed-files:
      - any-glob-to-any-file:
          - "**/audit/**/*"

# Token Management
area/token:
  - changed-files:
      - any-glob-to-any-file:
          - "**/token/**/*"
          - "**/jwt/**/*"

# Observability
area/observability:
  - changed-files:
      - any-glob-to-any-file:
          - "**/telemetry/**/*"
          - "**/metrics/**/*"
          - "**/tracing/**/*"
          - "**/logging/**/*"

# Repository label
repo/management:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*"
